# Spring Settings
spring:
  application:
    name: profile-service

  # Jackson Settings
  jackson:
    default-property-inclusion: non_null

  # Flyway Settings
  flyway:
    enabled: true
    default-schema: customer
    locations:
      - classpath:db/migration
    clean-disabled: true
    validate-on-migrate: true
    validate-migration-naming: true
    postgresql:
      transactional-lock: false

  # Datasource Settings
  datasource:
    url: jdbc:postgresql://localhost:5432/profiles
    username: postgres
    password: root

    # HikariCP Settings
    hikari:
      transaction-isolation: TRANSACTION_READ_COMMITTED
      auto-commit: false
      schema: customer
      minimum-idle: 32
      maximum-pool-size: 32
      max-lifetime: 600000

  # JPA Settings
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    open-in-view: false
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
          batch_size: 15
        order_inserts: true
        order_updates: true
        connection:
          provider_disables_autocommit: true
        query:
          in_clause_parameter_padding: true
          fail_on_pagination_over_collection_fetch: true
          plan_cache_max_size: 4096
        show_sql: false
        default_schema: customer
